### PR TITLE
@kanaabe: Leave middleware out of JoiQL core

### PR DESCRIPTION
**Pull request by craigspaeth**
This refactors JoiQL to not come with the middleware paradigm out of the box. Instead, you can add resolves to the `meta` property like we do with args. This should alleviate issues like https://github.com/muraljs/joiql/issues/9 and https://github.com/muraljs/joiql/issues/11 where the middleware approach isn't supporting all of GraphQL's features yet.  I'll then publish the middleware idea in a separate module.

e.g.

````javascript
const Article = object({
  title: string()
}).meta({
  resolve: (source, args) => db.articles.findOne({ _id: args.id })
})
````

### CODE REVIEW

**Comment by craigspaeth** [comment]
Not 100% sure these can be separate actually, going to close until I can get a separate middleware module working.

**Comment by craigspaeth** [comment]
Ok, I wrote the middleware module as a separate thing called [graphql-downup](https://github.com/muraljs/graphql-downup). Reopened.

**Comment by kanaabe** [comment]
@craigspaeth sorry for this huge delay, is it ok to merge this now?

**Comment by craigspaeth** [comment]
It is good to go! Be mindful this involves breaking changes when you update it in Positron.

**Comment by kanaabe** [comment]
👍🏼

**Pull request merged**
